### ISSUE TITLE
[Bug]: UI crash on Android

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#1109]
### Describe the bug

The app crashes on Android after various UI actions. These seem to be pure render issues, maybe in upstream react-native. Screen recording shows only one way to make the app crash among others.

### Reproduce

See screen recording.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/8538369/8cab2eff-0948-48b8-a0eb-68e0b47a6445

### Operating system

Android 13

### Bitkit version

master

### Log output

```shell
type: crash

osVersion: google/oriole/oriole:13/TQ2A.230505.002/2023052900:user/release-keys

package: to.synonym.bitkit.dev:46

process: to.synonym.bitkit.dev

processUptime: 9609 + 53 ms


java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1)

at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:2099)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4287)

at android.view.View.draw(View.java:23220)

at android.view.View.updateDisplayListIfDirty(View.java:22084)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.draw(View.java:23220)

at android.view.View.updateDisplayListIfDirty(View.java:22084)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.updateDisplayListIfDirty(View.java:22075)

at android.view.View.draw(View.java:22948)

at android.view.ViewGroup.drawChild(ViewGroup.java:4529)

at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)

at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)

at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)

at android.view.View.draw(View.java:23220)

at android.view.View.updateDisplayListIfDirty(View.java:22084)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)

at android.view.View.updateDisplayListIfDirty(View.java:22040)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)

at android.view.View.updateDisplayListIfDirty(View.java:22040)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)

at android.view.View.updateDisplayListIfDirty(View.java:22040)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)

at android.view.View.updateDisplayListIfDirty(View.java:22040)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)

at android.view.View.updateDisplayListIfDirty(View.java:22040)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)

at android.view.View.updateDisplayListIfDirty(View.java:22040)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)

at android.view.View.updateDisplayListIfDirty(View.java:22040)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)

at android.view.View.updateDisplayListIfDirty(View.java:22040)

at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)

at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)

at android.view.View.updateDisplayListIfDirty(View.java:22040)

at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)

at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)

at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)

at android.view.ViewRootImpl.draw(ViewRootImpl.java:4764)

at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4475)

at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3662)

at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2346)

at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9190)

at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)

at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)

at android.view.Choreographer.doCallbacks(Choreographer.java:899)

at android.view.Choreographer.doFrame(Choreographer.java:832)

at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)

at android.os.Handler.handleCallback(Handler.java:942)

at android.os.Handler.dispatchMessage(Handler.java:99)

at android.os.Looper.loopOnce(Looper.java:201)

at android.os.Looper.loop(Looper.java:288)

at android.app.ActivityThread.main(ActivityThread.java:7903)

at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)


```
```

**Comment by pwltr** [comment]
Tried updating some depdendencies to see if that fixes it, no success: 

```
diff --git a/package.json b/package.json
index 65bb006e..c9e3ee3e 100644
--- a/package.json
+++ b/package.json
@@ -41,7 +41,7 @@
     "@formatjs/intl-relativetimeformat": "^11.1.10",
     "@gorhom/bottom-sheet": "^4.4.7",
     "@react-native-clipboard/clipboard": "^1.11.2",
-    "@react-native-community/blur": "^4.3.0",
+    "@react-native-community/blur": "^4.3.2",
     "@react-native-community/netinfo": "^9.3.7",
     "@react-navigation/bottom-tabs": "^6.5.7",
     "@react-navigation/native": "^6.1.6",
@@ -78,14 +78,14 @@
     "lodash.debounce": "^4.0.8",
     "lodash.isequal": "^4.5.0",
     "lodash.throttle": "^4.1.1",
-    "lottie-react-native": "^5.1.5",
+    "lottie-react-native": "^5.1.6",
     "nodejs-mobile-react-native": "github:Shopify/nodejs-mobile-react-native#a74b13a8f92b39805611c3458e453e57e5abe98f",
     "process": "^0.11.10",
     "protobufjs": "^6.11.2",
     "random-access-web-storage": "^2.0.0",
     "react": "18.2.0",
     "react-i18next": "12.2.0",
-    "react-native": "0.71.7",
+    "react-native": "0.71.10",
     "react-native-biometrics": "2.2.2",
     "react-native-camera-kit": "14.0.0-beta2",
     "react-native-crypto": "^2.2.0",
@@ -95,7 +95,7 @@
     "react-native-draggable-flatlist": "^4.0.1",
     "react-native-exit-app": "^1.1.0",
     "react-native-fs": "^2.20.0",
-    "react-native-gesture-handler": "2.9.0",
+    "react-native-gesture-handler": "2.11.0",
     "react-native-haptic-feedback": "^1.14.0",
     "react-native-image-picker": "^5.1.0",
     "react-native-keyboard-accessory": "^0.1.16",
@@ -108,10 +108,10 @@
     "react-native-qrcode-svg": "^6.2.0",
     "react-native-randombytes": "^3.6.1",
     "react-native-rate": "^1.2.12",
-    "react-native-reanimated": "^3.1.0",
-    "react-native-reanimated-carousel": "3.1.5",
+    "react-native-reanimated": "^3.3.0-nightly-20230611-2426f3209",
+    "react-native-reanimated-carousel": "3.3.2",
     "react-native-restart": "^0.0.27",
-    "react-native-safe-area-context": "^4.5.0",
+    "react-native-safe-area-context": "^4.5.3",
     "react-native-screens": "^3.20.0",
     "react-native-share": "^8.2.1",
     "react-native-skia-stub": "github:limpbrains/react-native-skia-stub",
@@ -138,10 +138,10 @@
     "vm-browserify": "^1.1.2"
```
