### ISSUE TITLE
[Bug]: can't open channel with quick setup

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1489]
### Describe the bug

Pav and I opened channels with CJTI and it worked perfectly.

We then tried using onchain funds through quick setup:
- order id: e6f407d6-2596-48d9-b1bd-097b726490c8
- order id: 29e3f3b1-d66f-42e9-b54a-3835ce76b4ed

Error message:
warning: Order 29e3f3b1-d66f-42e9-b54a-3835ce76b4ed
Channel open failed. {"message":"The operation was unable to achieve a quorum during its retry window.","attempts":[{},{}],"name":"ExecutionError"}
:x: error: HTTP 500 blocktank-lsp-http
{"error":{"stack":"ExecutionError: The operation was unable to achieve a quorum during its retry window.\n    at Redlock._execute (/mnt/store/blocktank-v2/blocktank-lsp-http/service/node_modules/redlock/src/index.ts:462:15)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Redlock.acquire (/mnt/store/blocktank-v2/blocktank-lsp-http/service/node_modules/redlock/src/index.ts:309:28)\n    at Redlock.using (/mnt/store/blocktank-v2/blocktank-lsp-http/service/node_modules/redlock/src/index.ts:738:16)\n    at RedisLock.run (/mnt/store/blocktank-v2/blocktank-lsp-http/service/src/0_helpers/RedisLock.ts:27:16)\n    at Function.run (/mnt/store/blocktank-v2/blocktank-lsp-http/service/src/0_helpers/RedisLock.ts:46:20)\n    at Function.lock (/mnt/store/blocktank-v2/blocktank-lsp-http/service/src/1_database/entities/Order.entity.ts:166:16)\n    at Function.openChannel (/mnt/store/blocktank-v2/blocktank-lsp-http/service/src/2_order/OrderService.ts:24:5)\n    at /mnt/store/blocktank-v2/blocktank-lsp-http/service/src/3_api/http/api/channels.ts:267:7","message":"The operation was unable to achieve a quorum during its retry window.","attempts":[{},{}],"name":"ExecutionError"},"path":"/api/channels/29e3f3b1-d66f-42e9-b54a-3835ce76b4ed/open","method":"POST","body":{"connectionStringOrPubkey":"028558a62c97346217fbe5ba9db54efe2eafd956b4a9007b9856aa42c48eb1d5e0","announceChannel":false},"query":{},"params":{}}

### Operating system

GrapheneOS

### Bitkit version

v94

### Log output
[bitkit_ldk_logs_1705057442592.zip](https://github.com/synonymdev/bitkit/files/13918248/bitkit_ldk_logs_1705057442592.zip)

_No response_

**Comment by JeanlChristophe** [comment]
Fixed. Closing the ticket
