### ISSUE TITLE
[Bug]: Crash when scanning a QR that is not Electrum Server

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2288]
### Describe the bug

If a QR is scanned on the Electrum Server settings page that is not for an Electrum server Bitkit crashes.

### Reproduce

1. Go to Advanced -> Electrum Server
2. Tap scan QR button in top right
3. Scan a QR that is not an Electrum server (e.g. https://1ml.com/node/0296b2db342fcf87ea94d981757fdf4d3e545bd5cef4919f58b5d38dfdd73bf5c9)
4. Wait, Bitkit crashes.

### Screenshots / Recording

<img src="https://github.com/user-attachments/assets/2c76591e-6ca8-4102-ba33-46237d8e8dd2" width="250">

### Operating system

Android 14

### Bitkit version

0d67faa2509b1ec083d475abc80e90802f8d7d28

### Log output

```shell
com.facebook.react.common.JavascriptException:
RangeError: Maximum regex stack depth reached, js
engine: hermes, stack:
isValidURL@1:4259047
validateInput@1:4259220
onScan@1:4262457
onRead@1:4243962
onBarCodeRead@1:3778459
handleCodeRead@1:3784136
executeDispatchesAndReleaseTopLevel@1:416541
executeDispatch@1:413095
forEachAccumulated@1:414596
anonymous@1:416913
batchedUpdatesImpl@1:482299
batchedUpdates$1@1:416457
_receiveRootNodelDEvent@1:416745
receiveEvent@1:479604
_callFunction@1:144401
anonymous@1:142840
_guard@1:143782
callFunctionReturn Flushed Queue@1:142798
at
com.facebook.react.modules.core.ExceptionsManag erModule.reportException (Exceptions ManagerModul e.java:65)
at java.lang.reflect.Method.invoke(Native Method)
at
com.facebook.react.bridge.JavaMethodWrapper.invo ke(JavaMethodWrapper.java:372)
at
com.facebook.react.bridge.JavaModuleWrapper.invo ke(JavaModuleWrapper.java:146)
at com.facebook.jni. NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:958 )
at
android.os.Handler.dispatchMessage(Handler.java:9 9)
at
com.facebook.react.bridge.queue. MessageQueue Th readHandler.dispatchMessage(MessageQueueThrea dHandler.java:27)
at android.os.Looper.loopOnce(Looper.java:224) at android.os.Looper.loop(Looper.java:318)
at
com.facebook.react.bridge.queue. MessageQueue Th readImpl$4.run(MessageQueueThreadImpl.java:235) at java.lang.Thread.run(Thread.java:1012)
```

**Comment by catch-21** [comment]
Verified in b3f9f30dd56e4a1666492c3219f352d2bcd77086
No longer crashes, it will validate for url and use that to populate fields. If not valid url then it shows error toast.
